[build]
  command = ""
  publish = "."
  functions = "netlify/functions"

[context.production]
  environment = { CONTEXT = "production" }

[context.staging]
  environment = { CONTEXT = "staging" }

[[redirects]]
  from = "/api/send-chaos-scan-overview"
  to = "/.netlify/functions/send-chaos-scan-overview"
  status = 200

[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/send-contact"
  status = 200

[[redirects]]
  from = "/referral"
  to = "/referral.html"
  status = 200
